config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index, :show]

  resources :addresses, only: [:create, :new]

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  patch '/cart', to: 'cart#update'

  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create]

  get '/dashboard', to: 'users#show'

  get '/:slug', :to => 'categories#show', as: :category

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :users, only: [:edit, :update]
    resources :items, only: [:index, :edit, :update, :show]
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_item(item_id)
    contents[item_id.to_s] ||= 0
    contents[item_id.to_s] += 1
  end

  def total_items
    contents.values.sum
  end

  def total_price
    @contents.reduce(0) do |result, (item_id, quantity)|
      item = Item.find(item_id)
      result += item.price * quantity
      result
    end
  end

  def decrease_item(item_id)
    contents[item_id.to_s] -= 1
    contents.delete(item_id.to_s) if contents[item_id.to_s] == 0
  end

  def remove_item(item_id)
    contents.delete(item_id.to_s)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    @order = Order.new
    @items = @cart.contents
    @total_price = @cart.total_price
  end

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    flash[:success] = "Successfully added #{item.title} to your cart."
    redirect_back(fallback_location: cart_path)
  end

  def update
    item = Item.find(params[:item_id])
    @cart.decrease_item(item.id) if params[:change_type] == "decrease"
    @cart.add_item(item.id)      if params[:change_type] == "increase"
    # would need an else to catch any errors??
    session[:cart] = @cart.contents
    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:item_id])
    @cart.remove_item(item.id)
    flash[:success] = "Successfully removed #{view_context.link_to item.title, item_path(item)} from cart."
    session[:cart] = @cart.contents
    redirect_to cart_path
  end
end

app/views/cart/index.html.erb
<div class="container" style="background-color:#e7e8ce; padding: 20px;">
  <h2 class="cart_header"> Your Cart </h2>

  <%= render partial: "shared/order" %>

  <div class="row">
    <% if current_user %>
    <%= link_to "Checkout", orders_path, method: "post", class: "btn btn-success" %>
    <% else %>
    <%= link_to "Login", login_path %> or <%= link_to "Create Account", new_user_path %> to Checkout
    <% end %>
  </div>
</div>

app/views/cart/show.html.erb
<div class="container">
  <div class="displaypage">
    <h2 class="cart_header"> Your Cart </h2>
    <hr>
    <%= render partial: "shared/order" %>
    <div class="row">
      <% if current_user %>
        <% if !current_user.addresses.all.empty? %>
          <%= form_for @order do |f| %>
          <p><%= f.collection_select(:id, current_user.addresses.all, :id, :street, options = {:prompt => "Select an Address"}, class: "address_dropdown") %></p>
          <p><%= f.submit "Checkout", class: "btn btn-success" %></p>
          <% end %>
        <% end %>
        <%= link_to "Add a New Address", new_address_path %>
      <% else %>
        <%= link_to "Login", login_path %> or <%= link_to "Create Account", new_user_path %> to Checkout
      <% end %>
    </div>
  </div>
</div>