config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index, :show]

  resources :addresses, only: [:create, :new]

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  patch '/cart', to: 'cart#update'

  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create]

  get '/dashboard', to: 'users#show'

  get '/:slug', :to => 'categories#show', as: :category

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :users, only: [:edit, :update]
    resources :items, only: [:index, :edit, :update, :show]
  end
end

app/models/dashboard_helper.rb
module DashboardHelper

  def self.filter_orders(params)
    statuses = ["Ordered", "Paid", "Completed", "Cancelled"]
    if statuses.include?(params[:status])
      status = Status.find_by(name: params[:status])
      status.orders
    else
      Order.all
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def show
    @statuses = Status.left_outer_joins(:orders).select('statuses.*, COUNT(orders.*)').group('statuses.id')
    @orders = DashboardHelper.filter_orders(params)
    statuses = ["Ordered", "Paid", "Completed", "Cancelled"]
    if params[:status] && !statuses.include?(params[:status])
      flash[:warning] = "Filter does not exist"
    end
  end

  def update
    @order = Order.find(params[:order_id])
    if params[:change_status] == "Cancel"
      status = Status.find_by(name: "Cancelled")
    elsif params[:change_status] == "Paid"
      status = Status.find_by(name: "Paid")
    elsif params[:change_status] == "Completed"
      status = Status.find_by(name: "Completed")
    end
    if @order.update(status_id: status.id)
      flash[:success] = "Your order has been updated to be #{status.name}"
    else
      flash[:danger] = "Your order did not update."
    end
    redirect_to admin_dashboard_path
  end
end

app/views/admin/dashboard/show.html.erb
<div class="container">
  <div class="displaypage">
    <h2> Admin Dashboard </h2>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <h4>Order Statuses</h4>
        <div class="order-statuses">
          <% @statuses.each do |status| %>
            <li><%=link_to status.name.capitalize, admin_dashboard_path(status: status.name) %> <span class="tag tag-pill tag-default"> <%= status.orders.count %></span> </li>
          <% end %>
          <%= link_to "All Orders", admin_dashboard_path %>
        </div>
      </div>
      <div class="col-md-6">
        <h4>Orders</h4>
        <div class="order-list">
          <% @orders.each do |order| %>
            <li class="order_<%="#{order.id}"%>"><%= link_to "Order #{order.id} placed #{order.created_at.to_date}", order_path(order) %>
              <% if order.status.name == "Paid" || order.status.name == "Ordered" %>
                <%= link_to "Cancel", admin_dashboard_path(order_id: order.id, change_status: "Cancel"), method: "patch", class:"btn btn-danger btn-sm" %>
              <% end %>
              <% if order.status.name == "Ordered" %>
                <%= link_to "Paid", admin_dashboard_path(order_id: order.id, change_status: "Paid"), method: "patch", class:"btn btn-warning btn-sm " %>
              <% end %>
              <% if order.status.name == "Paid" %>
                <%= link_to "Completed", admin_dashboard_path(order_id: order.id, change_status: "Completed"), method: "patch", class:"btn btn-success btn-sm" %>
              <% end %>
            </li>
          <% end  %>
        </div>
      </div>
    </div>
    <%= link_to "Edit My Account", edit_admin_user_path(current_user) %> <br><%= link_to "Manage Items", admin_items_path %>
  </div>
</div>