config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index, :show]

  resources :addresses, only: [:create, :new]

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  patch '/cart', to: 'cart#update'

  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create]

  get '/dashboard', to: 'users#show'

  get '/:slug', :to => 'categories#show', as: :category

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :users, only: [:edit, :update]
    resources :items, only: [:index, :edit, :update, :show]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :status
  belongs_to :address
  has_many :order_items
  has_many :items, through: :order_items

  def order_total
    items.sum(:price)
  end

  def self.count_by_status
    group(:status).count
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.all
  end

  def show
    if current_admin?
      @order = Order.find(params[:id])
      @ordered_items = @order.items.group(:id).count
      @user = User.find_by(id: @order.user_id)
    elsif current_user && Order.find(params[:id]).user_id == current_user.id
      @order = current_user.orders.find(params[:id])
      @ordered_items = @order.items.group(:id).count
      @user = current_user
    else
      render file: '/public/404'
    end
  end

  def create
    @status = Status.where(name: "Ordered").first_or_create
    @order = Order.new(user: current_user, status: @status, address_id: params[:order][:id])
    @order_completion = OrderCompletion.new(@order, session[:cart])
    if @order_completion.create
      flash[:success] = "Thank you for placing your order"
      session.delete(:cart)
      redirect_to order_path(@order)
    else
      flash[:danger] = "Order did not submit"
      redirect_to cart_path
    end
  end

  private

  def order_params
    params.require(session[:cart]).permit(:address_id)
  end
end

app/views/orders/index.html.erb
<div class="container">
  <div class ="displaypage">
    <h2> <%= current_user.name.capitalize %>'s Order History </h2><hr>
    <% @orders.each do |order| %>
      <%= link_to "Order ##{order.id} placed #{order.created_at.to_date}", order_path(order) %><br>
    <% end %><hr>
    <h4>
      <% if current_admin? %>
        <%= link_to "Back to your account page", admin_dashboard_path %>
      <% else %>
        <%= link_to "Back to your account page", dashboard_path %>
      <% end %>
    </h4>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="displaypage">
    <h2 class="cart_header">Order <%= @order.id %></h2>
    <h4 class="cart_header"> Placed <%= @order.created_at.to_date %> by <%= @user.name.capitalize %></h4>
    <hr>
    <% @ordered_items.each do |id, count| %>
      <div class="row">
        <div class="col-md-3"></div>
        <% item = find_item(id) %>
        <div class="item_<%= item.id %>">
          <div class="col-md-3">
            <%= image_tag(item.image, class: "img-thumbnail") %>
          </div>
          <div class="col-md-6" style="text-align: left">
            <p>Title: <%= link_to item.title, item_path(item) %></p>
            <p>Price: <span style="color: #a55538"> <%= number_to_currency(item.price) %> </span></p>
            <p>Description: <%= item.description %></p>
            <p>Quantity: <%= count %> </p>
            <p>Subtotal: <%= calculate_subtotal(item.price, count) %></p>
          </div>
        </div>
      </div><hr>
    <% end %>
    <div class="row">
      <span style="color: #a55538"> Total: <%= number_to_currency(@order.order_total) %></span>
    </div>
    <br>
    <p>Order Status: <strong><%= @order.status.name.capitalize %></strong> <%= @order.status.created_at %></p>
    <strong>Shipping To:</strong> <br><%= @order.address.street %><br>
    <%= @order.address.city %>, <%= @order.address.state %><br>
    <%= @order.address.zip %><br>
    <hr>
    <h4>
      <% if current_admin? %>
        <%= link_to "Back to Dashboard", admin_dashboard_path %>
      <% else %>
        <%= link_to "Back to Order History", orders_path %>
      <% end %>
    </h4>
  </div>
</div>