config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index, :show]

  resources :addresses, only: [:create, :new]

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  patch '/cart', to: 'cart#update'

  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create]

  get '/dashboard', to: 'users#show'

  get '/:slug', :to => 'categories#show', as: :category

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :users, only: [:edit, :update]
    resources :items, only: [:index, :edit, :update, :show]
  end
end

app/views/layouts/_navbar.html.erb
<div class="navbar-default">
  <nav class="navbar navbar-default">
    <a class="navbar-brand" href="/">Root <span style="font-family: 'Bungee Outline', cursive;">&</span> Branch</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
        <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
          <% all_categories.each do |category| %>
            <%= link_to category.name, category_path(category), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/items">All  Items</a>
      </li>
    </ul>
    <ul class="nav navbar-nav float-xs-right">
      <li class="nav-item">
        <%= link_to "Cart (#{@cart.total_items})", cart_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if current_admin? %>
          <%= link_to "Account", admin_dashboard_path, class: "nav-link" %>
        <% elsif current_user %>
          <%= link_to "Account", dashboard_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if current_user %>
          <%= link_to "Logout #{current_user.name}", logout_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", login_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html align="center">
  <head>
    <title>Root & Branch</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Hairline|Bungee+Inline|Bungee+Outline" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,200,400" rel="stylesheet">
  </head>
  <%= render partial: "layouts/navbar" %>

  <% flash.each do |type, message| %>
    <%= content_tag :div, sanitize(message), class: "alert-#{type}" %>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>